security:
    encoders:
         App\Entity\Users: 'auto'
    providers:
         database_users:
            entity: { class: App\Entity\Users, property: login }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: index
                username_parameter: login
                password_parameter: password
            logout:
                path: security_logout
                target: security_login
#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }